TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += isorbhp.db
DATA += isorbhp.proto

#=======================================
include $(TOP)/configure/RULES
